# Generated by Django 5.2.7 on 2025-10-26 11:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0002_house_securitycompliance_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='house',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
