# Generated by Django 4.2.25 on 2025-10-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0003_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='house',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='QR code data string for scanning'),
        ),
    ]
