# Generated by Django 5.2.7 on 2025-10-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0003_house_date_registered_house_qr_code_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycompliance',
            name='route_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='securitycompliance',
            name='scanned_houses',
            field=models.ManyToManyField(blank=True, related_name='scanned_records', to='adminstrator.house'),
        ),
    ]
