# Generated by Django 5.2.7 on 2025-10-27 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0004_securitycompliance_route_completed_and_more'),
        ('security', '0004_securityprofile_assigned_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, help_text='Comments about the scan (condition, issues, observations)')),
                ('scan_status', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial Scan'), ('missed', 'Missed'), ('issue_found', 'Issue Found')], default='completed', max_length=20)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('compliance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_scans', to='adminstrator.securitycompliance')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_records', to='adminstrator.house')),
                ('security_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_scans', to='security.securityprofile')),
            ],
            options={
                'verbose_name': 'House Scan',
                'verbose_name_plural': 'House Scans',
                'ordering': ['-scan_time'],
                'unique_together': {('compliance_record', 'house')},
            },
        ),
    ]
