# Generated by Django 4.2.25 on 2025-10-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_panicalert'),
        ('adminstrator', '0004_house_qr_code_house_qr_code_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='checkpoints',
            field=models.ManyToManyField(blank=True, related_name='routes', to='members.userprofile'),
        ),
    ]
