# Generated by Django 4.2.25 on 2025-10-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0005_alter_route_checkpoints'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['assigned_security_guard'], name='adminstrato_assigne_3f73e1_idx'),
        ),
    ]
