# Generated by Django 5.2.7 on 2025-10-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyalert',
            name='user',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='user',
        ),
        migrations.DeleteModel(
            name='PatrolStat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='subscription_active',
        ),
        migrations.DeleteModel(
            name='EmergencyAlert',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
    ]
