# Generated by Django 5.2.7 on 2025-10-26 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address', models.TextField(blank=True)),
                ('emergency_type', models.CharField(choices=[('general', 'General Emergency'), ('medical', 'Medical Emergency'), ('fire', 'Fire'), ('intruder', 'Intruder'), ('accident', 'Accident'), ('other', 'Other')], default='general', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panic_events', to='members.memberprofile')),
            ],
            options={
                'verbose_name': 'Panic Event',
                'verbose_name_plural': 'Panic Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
