# Generated by Django 4.2.25 on 2025-10-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_panicalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='QR code data string for scanning'),
        ),
    ]
