# Generated by Django 5.2.7 on 2025-10-26 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminstrator', '0003_house_date_registered_house_qr_code_data'),
        ('security', '0002_securityprofile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_routes', to=settings.AUTH_USER_MODEL)),
                ('houses', models.ManyToManyField(related_name='patrol_routes', to='adminstrator.house')),
            ],
            options={
                'verbose_name': 'Patrol Route',
                'verbose_name_plural': 'Patrol Routes',
                'ordering': ['-created_at'],
            },
        ),
    ]
