# Generated by Django 5.2.7 on 2025-10-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_securityprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityprofile',
            name='role',
            field=models.CharField(default='security', max_length=20),
        ),
    ]
