# Generated by Django 4.2.25 on 2025-10-30 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_securityprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.TextField()),
                ('route_id', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('security_guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='security.securityprofile')),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
