# Generated by Django 4.2.25 on 2025-10-30 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_scanlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanlog',
            name='route_id',
        ),
    ]
