# Generated by Django 4.2.25 on 2025-10-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_remove_scanlog_route_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['security_guard', 'scanned_at'], name='security_sc_securit_666fbd_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['scanned_at'], name='security_sc_scanned_293d54_idx'),
        ),
    ]
